### ISSUE TITLE
pf-popover development

### ISSUE THREAD

**Issue by priley86** [patternfly-webcomponents/patternfly-webcomponents#26]
A popover component is needed which matches the functionality of our [Patternfly popover](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/popovers.html). Popover should expose the same JS API as the one [here](http://thednp.github.io/bootstrap.native/#componentPopover) if possible.

**Comment by cdcabrera** [comment]
@sahil143 developing, see PR #50

**Comment by priley86** [comment]
This component has been merged.
