### ISSUE TITLE
pf-modal development

### ISSUE THREAD

**Issue by priley86** [patternfly-webcomponents/patternfly-webcomponents#29]
A modal component is needed which matches the functionality of our Patternfly [modal](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/modals.html). Modal should expose the same JS API as the one [here](https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/modals.html) if possible.

**Comment by LHinson** [comment]
@dabeng I've also created a story for this to track it in our PatternFly sprint. Are you interested in picking this one up? https://patternfly.atlassian.net/browse/PTNFLY-2277

**Comment by dabeng** [comment]
@bleathem @priley86 @LHinson Would you like to review this [PR](https://github.com/patternfly-webcomponents/patternfly-webcomponents/pull/33)?

**Comment by priley86** [comment]
The initial PR for `pf-modal` has been merged. Will track any updates to the modal in future PRs/issues. Closing this issue.
