### ISSUE TITLE
display issues about tooltip

### ISSUE THREAD

**Issue by dabeng** [patternfly-webcomponents/patternfly-webcomponents#31]
<img width="388" alt="screen shot 2017-03-14 at 2 45 42 pm" src="https://cloud.githubusercontent.com/assets/5689075/23888856/01014ff2-08c5-11e7-9e5e-667d39c9d8b1.png">

<img width="359" alt="screen shot 2017-03-14 at 2 45 57 pm" src="https://cloud.githubusercontent.com/assets/5689075/23888873/100b1140-08c5-11e7-89ab-7a6ccef99109.png">

**Comment by priley86** [comment]
@dabeng this is just because the iframe size is off :( .. i will resize it and reference this issue in a future PR 😄
