### ISSUE TITLE
React demo components don't render

### ISSUE THREAD

**Issue by yunyu** [patternfly-webcomponents/patternfly-webcomponents#43]
Page: https://patternfly-webcomponents.github.io/react.html

Errors in console:

![](https://i.imgur.com/UfVj0Y6.png)

**Comment by priley86** [comment]
@yunyu thanks for reporting this! This was definitely missed after our v1 merge...

I've updated the site references just now... let me know if you see any more issues!

**Comment by priley86** [comment]
https://github.com/patternfly-webcomponents/patternfly-webcomponents.github.io/commit/9b4e38556f96053e9f57408737bf879a331dcb82
