### ISSUE TITLE
Travis using very old version of chrome for testing

### ISSUE THREAD

**Issue by Agathver** [patternfly-webcomponents/patternfly-webcomponents#45]
Precise machines come with Chromium 37.0. Tests using mutation observers are failing.

I would propose using newer versions of chrome (with headless support) on trusty images, as precise is EOL and cannot install newer chrome versions.

**Comment by priley86** [comment]
we're resolving this in #46 . should be closed soon...

**Comment by cdcabrera** [comment]
There appears to be an additional issue with users running unit tests locally and having versions of Chrome older than V59, and using the ```headless chrome``` update 

Have a solution we can use as a follow up, see PR #49

**Comment by priley86** [comment]
Closing. These PRs have been merged so this should be resolved...
