### ISSUE TITLE
We'd better keep jQuery in webcomponents version of patternfly

### ISSUE THREAD

**Issue by dabeng** [patternfly-webcomponents/patternfly-webcomponents#8]
I don't think jQuery is in conflict with ES2015 or Web Components. In fact, jQuery can save us a lot of effort to handle dom modification, node searching or event bindings. We just need to introduce jQuery as a helper object with 
```js
import $ from 'jquery';
```
Maybe you guys can imagine that how short the code lines will be if we refctor the folowing code snippets with jQuery.
```js
  _initPersistent () {
    let self = this;
    let nodes = this._getNodes('button.close');
    let el = nodes[0];
    if (this.getAttribute("persistent") === "true") {
      this.classList.add("alert-dismissable");
      if (el !== undefined) {
        el.classList.remove("hidden");
        el.setAttribute('onclick', this.getAttribute("persistent-callback-fn"));
      }
    } else {
      this.classList.remove("alert-dismissable");
      if (el !== undefined) {
        el.classList.add("hidden");
      }
    }
  }
```

**Comment by dabeng** [comment]
As for the other sections of patternfly-webcomponents, for example: ajax, OO machanism, aysnc operations. Native js, especially the new APIs provided by ES2015 is the best choice rather than jQuery.

**Comment by priley86** [comment]
I disagree with adding a dependency on jQuery. We are actively trying to remove jQuery from our project where easily possible. If a js helper routine is frequently used, we can add it in pf-utils or load it individually (should be no need to load a monolithic helper library like jQuery unless you are writing a legacy component). The idea long term is to split components into their own npm packages, so a jQuery dependency in one component is less problematic for others.

**Comment by dabeng** [comment]
The original intension was that I don't want pf-utils to be the next jQuery. It is likely that we make much effort to produce many scattered, common helper methods, but they don't work well in performance, security and cross-browser than their jQuery equivalents.

**Comment by priley86** [comment]
While jQuery was great during its heyday, many of its core routines are becoming built into javascript with es6. Once transpiled to es5, many of these routines work natively in IE10 and up browsers (look at the Polymer project or the Onsen.io project if you want to see examples of components written without jQuery). We've been looking at these a lot during our planning for web components and believe this browser is the lowest common denominator we'll need to support once web components are production ready.

**Comment by dabeng** [comment]
All right, let's embrace standalone patternfly-webcomponenents without worry :)

**Comment by priley86** [comment]
@dabeng to follow up on this - i've introduced #14 today that shows an example of removing jQuery completely and using vanilla js. This component is based on the [boostrap native project](https://github.com/thednp/bootstrap.native), only converted to es6 and a web component. You can see a lot more examples of vanilla components in that project though.

**Comment by priley86** [comment]
@dabeng if you'd like to see an example shim in React or Angular, those are coming soon too.
