### ISSUE TITLE
Are we planning to refator the whole patternfly widdgets with Web Components?

### ISSUE THREAD

**Issue by dabeng** [patternfly-webcomponents/patternfly-webcomponents#9]
If this is the case, I wanna know when is the webcomponents version of Datatables released? There is no doubt it's the most important plugin in my daily development.

**Comment by priley86** [comment]
We are planning to implement many new behaviors in web components for PF5 (planned after PF4 Angular upgrades). These new web-components will likely fit in closely with the patternfly-atomic effort and come around shortly after.

**Comment by dabeng** [comment]
I got it. Thanks a lot.
